---
title       : White Wine Quality
subtitle    : Prediction of quality based on physiochemical features
author      : Justin Nafe
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Introduction

1. Predict quality of white wine based on physicochemical features.
2. Random Forest algorithm for the prediction.
3. Accuracy for the measure of success.

--- 

## Benifits

1. Algorithmically determine quality of wine.
2. Limit human interaction in determining quality of wine.
  * For example, winemakers could reduce the number of times humans are used to determine quality of wine, stop production of poor wine, and/or taste test only the wines that predict high quality.

--- 

## Accuracy and Precision

```{r echo=FALSE, results='hide'}
library(caret)
library(randomForest)
library(e1071)

whitewine <- read.csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv", sep=";")
whitewine$quality <- factor(whitewine$quality)

importantCols <- c("alcohol", "density", "volatile.acidity", "free.sulfur.dioxide", "quality")
dataset <- whitewine[, importantCols]
fullDataset <- whitewine

qualColWhite <- grep("quality", colnames(dataset))
fullQualColWhite <- grep("quality", colnames(fullDataset))

dataset[,-qualColWhite] <- log(dataset[,-qualColWhite] + 1 - min(dataset[,-qualColWhite]))
fullDataset[,-fullQualColWhite] <- log(fullDataset[,-fullQualColWhite] + 1 - min(fullDataset[,-fullQualColWhite]))

set.seed(78490)
inTrainWhite <- createDataPartition(y=dataset$quality,
                                    p=0.80, list=FALSE)

training <- dataset[inTrainWhite,]
testing <- dataset[-inTrainWhite,]
mtryGrid <- expand.grid(mtry = 2)
fitControl <- trainControl(method = "cv", number = 10)
set.seed(78490)
model <- train(quality~., data=training, method = "rf", trControl = fitControl, tuneGrid = mtryGrid)


pred <- predict(model, testing)
missClass = function(values,prediction){
  sum(prediction == values) / length(values)
}
accuracy <- missClass(as.numeric(testing$quality), as.numeric(predict(model, testing)))


set.seed(78490)
inTrainWhite <- createDataPartition(y=fullDataset$quality,
                                    p=0.80, list=FALSE)

training <- fullDataset[inTrainWhite,]
testing <- fullDataset[-inTrainWhite,]
mtryGrid <- expand.grid(mtry = 2)
fitControl <- trainControl(method = "cv", number = 10)
set.seed(78490)
model <- train(quality~., data=training, method = "rf", trControl = fitControl, tuneGrid = mtryGrid)


pred <- predict(model, testing)
fullAccuracy <- missClass(as.numeric(testing$quality), as.numeric(predict(model, testing)))
```

1. Predicting using the top 4 features (the top 4 features were determined by having the most predictability out of the 11 features. Please review wineQualityAnalysis.Rmd for how these were derived), accuracy was `r accuracy`
2. Predicting using all 11 features, accuracy was `r fullAccuracy`

---

## References

P. Cortez, A. Cerdeira, F. Almeida, T. Matos and J. Reis. 
Modeling wine preferences by data mining from physicochemical properties. In Decision Support Systems, Elsevier, 47(4):547-553, 2009

Shiny app
https://justinnafe.shinyapps.io/WineQualityAnalysis

White Wine Quality Analysis
http://justinnafe.github.io/wine-quality-analysis/wineQualityAnalysis.html 
